Repository TFTrc/TFTirc, pull requests merged in 2024-08, with the labels that each got.

#4 Feature/parser
  Parser.cpp
  Parser.hpp
Labels: enhancement

#5 서버 클래스 구현 #2
  Makefile
  Server.cpp
  Server.hpp
  main.cpp
Labels: enhancement

#11 Parser 기능 수정 및 Server 객체 수정
  Client.cpp
  Client.hpp
  Makefile
  Parser.cpp
  Parser.hpp
  Server.cpp
  Server.hpp
Labels: enhancement

#20 feat:NICK 구현
  Commands/NICK.cpp
  Commands/NICK.hpp
Labels: enhancement

#21 채널 클래스 구현
  Channel.cpp
  Channel.hpp
  Server.cpp
  Server.hpp
Labels: enhancement

#23 feat: USER 커맨드 구현
  Commands/USER.cpp
  Commands/USER.hpp
Labels: enhancement

#33 [refactor] Channel 클래스 멤버 변수 타입 변경
  Channel.cpp
  Channel.hpp
  Makefile
  Server.cpp
  Server.hpp
Labels: enhancement

#35 Feature/nick user bugfix #34
  Client.cpp
  Client.hpp
  Commands/CommandController.cpp
  Commands/NICK.cpp
  Commands/NICK.hpp
  Commands/USER.cpp
  Commands/USER.hpp
  Server.cpp
  Server.hpp
Labels: bug

#37 Feature/make numeric msg #36
  Commands/Command.cpp
  Commands/Command.hpp
  Commands/NICK.cpp
  Commands/NICK.hpp
  Commands/USER.cpp
  Commands/USER.hpp
Labels: enhancement

#39 서버, 채널 클래스 구현 요구사항 반영
  Client.cpp
  Client.hpp
  Server.cpp
  Server.hpp
Labels: enhancement

#45 [hotfix] Client 메소드 수정
  Client.cpp
  Client.hpp
Labels: bug

#42 Feature/privmsg 구현 완료
  Commands/Command.cpp
  Commands/Command.hpp
  Commands/CommandController.cpp
  Commands/PRIVMSG.cpp
  Commands/PRIVMSG.hpp
Labels: enhancement

#46 [hotfix] accept 메소드에 클라이언드 주소구조체 크기 전달
  Server.cpp
Labels: bug

#47 커맨드 컨트롤러의 cmdSplit 함수 수정
  Client.hpp
  Commands/CommandController.cpp
  Commands/CommandController.hpp
Labels: bug, enhancement

#54 [Refactor] 클래스 메소드 수정 및 예외처리 추가 (#48, #49)
  Channel.cpp
  Channel.hpp
  Client.cpp
  Server.cpp
Labels: bug, enhancement

#56 PRIVMSG, JOIN메서드에 broadcast 적용
  Commands/JOIN.cpp
  Commands/PRIVMSG.cpp
  Makefile
Labels: enhancement

#57 feat: MODE implementation
  Commands/MODE.cpp
  Commands/MODE.hpp
  Commands/PASS.cpp
  Makefile
Labels: enhancement

#62 JOIN명령어 INVITE_ONLY에서 isInvite() 로직 추가
  Commands/JOIN.cpp
Labels: enhancement

#67 [Feat] 채널 관련 커맨드 구현
  Channel.cpp
  Channel.hpp
  Commands/INVITE.cpp
  Commands/INVITE.hpp
  Commands/KICK.cpp
  Commands/KICK.hpp
  Commands/PART.cpp
  Commands/PART.hpp
  Commands/TOPIC.cpp
  Commands/TOPIC.hpp
Labels: enhancement

#68 존재하지 않는 커맨드 입력 시 처리용 클래스 UNKNOWN추가
  Commands/Command.cpp
  Commands/Command.hpp
  Commands/CommandController.cpp
  Commands/UNKNOWN.cpp
  Commands/UNKNOWN.hpp
Labels: enhancement

#71 bugfix : 존재하지 않는 명령어를 UNKNOWN으로 출력하는 버그 수정
  Commands/CommandController.cpp
Labels: bug

#74 클라이언트가 빈문자열 넣을 떄 에러처리 && Makefile에 UNKNOWN.cpp 추가
  Commands/CommandController.cpp
  Makefile
Labels: bug

#75 [Refactor] 클라이언트 연결 해제
  Channel.cpp
  Channel.hpp
  Server.cpp
  Server.hpp
Labels: bug, enhancement

#76 [Hotfix] 세미콜론 오타 제거
  Server.cpp
Labels: bug

#80 Feature/command notregister method #58
  Commands/Command.cpp
  Commands/Command.hpp
  Commands/JOIN.cpp
Labels: enhancement

#82 JOIN, NICK 기능추가 및 버그수정
  Commands/Command.cpp
  Commands/NICK.cpp
Labels: bug, enhancement

#86 [Refactor] 새로운 커맨드 버그 수정 및 디버거 연결
  Channel.cpp
  Channel.hpp
  Client.cpp
  Client.hpp
  Commands/Command.cpp
  Commands/Command.hpp
  Commands/CommandController.cpp
  Commands/INVITE.cpp
  Commands/KICK.cpp
  Commands/PART.cpp
  Commands/PART.hpp
  Commands/TOPIC.cpp
  Server.cpp
  Server.hpp
Labels: bug, enhancement

#96 MODE 브로드캐스트, _flag 변경
  Channel.cpp
  Commands/MODE.cpp
  Commands/MODE.hpp
Labels: bug

#104 [Feat] Client 인증상태 및 접근 메소드 추가 (#97)
  Client.cpp
  Client.hpp
Labels: enhancement

#105 [Fix] 명령어 발신메세지 수정
  Channel.cpp
  Channel.hpp
  Commands/INVITE.cpp
  Commands/KICK.cpp
  Commands/TOPIC.cpp
Labels: bug, enhancement

#108 [Fix] 커맨드 자잘한 버그 수정
  Channel.cpp
  Server.cpp
Labels: bug

#110 fix: topic 콜론 처리방식 수정
  Channel.cpp
  Commands/TOPIC.cpp
Labels: bug

#118 [Refactor] Server 내 Client, Channel 저장 방식 수정
  Channel.cpp
  Client.cpp
  Commands/INVITE.cpp
  Server.cpp
  Server.hpp
Labels: bug, enhancement

#127 [Fix] 버그 수정
  Channel.cpp
  Channel.hpp
  Commands/KICK.cpp
  Commands/TOPIC.cpp
  Server.cpp
Labels: bug

#135 [Fix] Channel 초대인자 변경
  Channel.cpp
  Channel.hpp
  Commands/INVITE.cpp
  Commands/JOIN.cpp
  Server.cpp
Labels: bug, enhancement

#136 [Fix] 프로그램 메인 인자검증 로직 수정
  main.cpp
Labels: bug

#140 [Feat] Channel 내 추가메소드 구현
  Channel.cpp
  Channel.hpp
Labels: enhancement

#139 fix : mode +o error
  Commands/MODE.cpp
  Commands/MODE.hpp
  Server.cpp
Labels: bug

#150 [Hotfix] 디버그 메세지 수정 및 Topic 로직 수정
  Commands/TOPIC.cpp
  Server.cpp
  Server.hpp
Labels: bug
